name: Windows RDP via Tailscale (A)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Windows RDP via Tailscale (B)"]
    types:
      - completed

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Install Tailscale (via choco)
        run: choco install tailscale -y --no-progress

      - name: Enable RDP + user + firewall
        run: |
          $ErrorActionPreference = 'Stop'
          $u='Bullettemporary'; $p='Bullet@12345'
          $sec = ConvertTo-SecureString $p -AsPlainText -Force
          if (-not (Get-LocalUser -Name $u -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name $u -Password $sec -AccountNeverExpires -PasswordNeverExpires:$true
            Add-LocalGroupMember -Group Administrators -Member $u
            Add-LocalGroupMember -Group "Remote Desktop Users" -Member $u
          } else {
            Set-LocalUser -Name $u -Password $sec -AccountNeverExpires:$true
            Enable-LocalUser -Name $u
          }
          Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop" | Out-Null

      - name: Cleanup old device from Tailscale
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          Invoke-RestMethod -Method GET -Uri "https://api.tailscale.com/api/v2/tailnet/zatchati0@gmail.com/devices" `
            -Headers @{Authorization="Bearer tskey-api-k8k6TMrxJD21CNTRL-UZ4q4DdnFicBmuLEc4DqicCcr34WBQkrC"} |
            ForEach-Object {
              if ($_.hostname -eq "bullet") {
                Invoke-RestMethod -Method DELETE -Uri "https://api.tailscale.com/api/v2/device/$($_.id)" `
                  -Headers @{Authorization="Bearer tskey-api-k8k6TMrxJD21CNTRL-UZ4q4DdnFicBmuLEc4DqicCcr34WBQkrC"}
              }
            }

      - name: Tailscale up (fixed hostname)
        run: |
          $ErrorActionPreference = 'Stop'
          tailscale up --auth-key tskey-auth-kCBNtpbt3H11CNTRL-rJdYwx6bnR59Gj4ivN4DR5JKvahLZ5ML --hostname bullet --accept-routes --accept-dns=false
          Start-Sleep -Seconds 5
          tailscale ip -4
          tailscale ip -6
          Write-Host "================ RDP CONNECT ================"
          Write-Host "Hostname : bullet"
          Write-Host "Username : Bullettemporary"
          Write-Host "Password : Bullet@12345"
          Write-Host "============================================="

      - name: Keep alive (~5h 55m) & pre-dispatch partner (B)
        run: |
          $until = (Get-Date).AddMinutes(355)
          while ((Get-Date) -lt $until) {
            Write-Host "[$(Get-Date -Format 'HH:mm:ss')] RDP alive.."
            Start-Sleep -Seconds 60
          }
          Invoke-RestMethod -Method POST `
            -Uri https://api.github.com/repos/${{ github.repository }}/actions/workflows/windows-rdp-tailscale-B.yml/dispatches `
            -Headers @{Authorization="token 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"} `
            -Body '{"ref":"main"}'
